import com.vungle.mediation.VungleBannerAdapter.isRequestPending
import com.google.android.gms.ads.mediation.MediationInterstitialAdConfiguration
import com.google.android.gms.ads.mediation.MediationAdLoadCallback
import com.google.android.gms.ads.mediation.MediationInterstitialAd
import com.google.android.gms.ads.mediation.MediationInterstitialAdCallback
import com.vungle.ads.AdConfig
import android.os.Bundle
import com.google.ads.mediation.vungle.VungleMediationAdapter
import android.text.TextUtils
import com.google.android.gms.ads.AdError
import com.vungle.mediation.VungleManager
import com.vungle.mediation.AdapterParametersParser
import com.vungle.mediation.VungleExtrasBuilder
import com.vungle.mediation.VungleBannerAdapter
import com.google.ads.mediation.vungle.VungleBannerAd